campaignMainContainer = 'class=campaign'
featuredCampaignContainer = 'id=campaignFeatured'
featureCampaignBuyNowButton = 'xpath=//*[@class="ui-btn ui-btn--phantom"]'
commonCampaignsContainer = 'id=campaignNew'
secondCampaignButton = 'xpath=(//div[contains(text(),"Compre agora")])[2]'
campaingHeaderSection = 'class=campaign-overview__content'
gridOfProducts = 'xpath=//*[@class="cdp__grid-row"]'
facebookSharingButton = 'xpath=//*[@class="qa-sharing-facebook js-facebook-feed ui-sharing__button ui-sharing__button--facebook"]'
messengerSharingButton = 'xpath=//*[@class="qa-sharing-facebook-messenger js-facebook-send ui-sharing__button ui-sharing__button--facebook-messenger"]'
emailSharingButton = 'xpath=//*[@class="qa-sharing-mail ui-sharing__button ui-sharing__button--mail"]'
campaignFilter = 'class=select-current'
priceFilter = '//*[@class="select-menu__container select-menu__container--active"]/li[2]'
