buttonSignUp = "css=.signup-resp__main__button--login, .signup-resp__main__button--signup"
emailTextField = "id=signup-resp__form__input--email"
passwordTextField = "id=signup-resp__form__input--password"
acceptedTerms = "css=.signup-resp__form__checkbox-label, .signup-resp__form__forgot-password"
buttonAccountCreate = "css=.signup-resp__main__button--continue, .signup-resp__main__button--entry--login, .signup-resp__main__button--entry--signup"
myAccount = "css=body.is-desktop.is-logged-in, body.is-tablet.is-logged-in"
emailTextFieldError="css=.signup-resp__input-error-message.signup-resp__input-error-message--email"
passwordTextFieldError = "css=.signup-resp__input-error-message"
notAcceptTermsError = "css=.signup-resp__form__checkbox-label"
